name: pr_check
on:
  pull_request:
permissions:
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Repository Dispatch
      uses: myrotvorets/trigger-repository-dispatch-action@1.0.0
      with:
        token: ${{ secrets.TRIGGER_EVENT }}
        repo: jensh007/test1
        type: ocm_pr
        payload: '{ "ref": "${{ github.ref }}", "sha": "${{ github.sha }}" }'
    - uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: 1,
            owner: jensh007,
            repo: test1,
            body: 'Test results go here!'
            })