name: pr_check
on:
  pull_request:
permissions:
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Repository Dispatch
      uses: myrotvorets/trigger-repository-dispatch-action@1.0.0
      with:
        token: ${{ secrets.TRIGGER_EVENT }}
        repo: jensh007/test1
        type: ocm_pr
        payload: '{ "ref": "${{ github.ref }}", "sha": "${{ github.sha }}" }'
